# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e415143fe0531ec1d1991032f220f3c5dbe8201143d46cbb1d5fde13be96f804c368d0f0489b1089820fbac1cfbe5860ba14f6b59ed00a2cf9d5125e568b1887

test:
  secret_key_base: 99beb88fba2009a0424e70ae2a35b6bbd53b658bf3fc3761cd09e39b65f3031b64ea33d13163053b648f9036a424a45bec99e464c8d6d23decee3bb5a8e4dd32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
